#!/usr/bin/env python3
import argparse
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_grid_file(filepath: Path):
    with filepath.open("rb") as f:
        data = pickle.load(f)
    return data


def plot_heatmap(data, output_path: Path):
    x_values = np.array(data["x_values"], dtype=float)
    y_values = np.array(data["y_values"], dtype=float)
    avg_matrix = np.array(data["average_active_fraction"], dtype=float)
    std_matrix = np.array(data.get("std_active_fraction", []), dtype=float)

    def draw_matrix(ax, matrix, label):
        c = ax.imshow(matrix, origin="lower", aspect="auto", cmap="viridis")
        fig.colorbar(c, ax=ax, label=label)
        ax.set_xticks(np.arange(len(y_values)))
        ax.set_yticks(np.arange(len(x_values)))
        ax.set_xticklabels([f"{v:.3g}" for v in y_values], rotation=45, ha="right")
        ax.set_yticklabels([f"{v:.3g}" for v in x_values])
        ax.set_xlabel(data["param_y"].replace("_", " "))
        ax.set_ylabel(data["param_x"].replace("_", " "))
        ax.grid(False)
        return c

    if std_matrix.size == 0:
        fig, ax = plt.subplots(figsize=(10, 8))
        draw_matrix(ax, avg_matrix, "Avg active cell fraction")
        ax.set_title(
            f"Avg active fraction: {data['param_x']} vs {data['param_y']}"
            f"\nFixed: {', '.join(f'{k}={v}' for k, v in data['fixed_params'].items())}"
        )
    else:
        fig, axes = plt.subplots(1, 2, figsize=(18, 8))
        draw_matrix(axes[0], avg_matrix, "Avg active cell fraction")
        axes[0].set_title("Average active cell fraction")
        draw_matrix(axes[1], std_matrix, "Std dev active fraction")
        axes[1].set_title("Std dev of active cell fraction")
        fig.suptitle(
            f"{data['param_x']} vs {data['param_y']}\nFixed: {', '.join(f'{k}={v}' for k, v in data['fixed_params'].items())}",
            fontsize=14,
        )

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved heatmap to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Plot parameter grid heatmap files.")
    parser.add_argument(
        "files",
        nargs="+",
        help="Path(s) to grid result files generated by run_parameter_grid.py",
    )
    parser.add_argument(
        "--output-dir",
        default="./plots",
        help="Directory to save generated heatmap images.",
    )
    args = parser.parse_args()

    for filepath in args.files:
        file_path = Path(filepath)
        data = load_grid_file(file_path)
        output_file = Path(args.output_dir) / f"heatmap_{file_path.stem}.png"
        plot_heatmap(data, output_file)


if __name__ == "__main__":
    main()
